### ISSUE TITLE
open previous feed

### ISSUE THREAD

**Issue by who-am-1** [teddy-gustiaux/youtube-rss-finder#3]
after adding meny subscriptions this opens the previous subscription, after closing rss tab and press rss-finder icon again, it's open properly feed

**Comment by teddy-gustiaux** [comment]
Thanks for opening an issue! The add-on does not handle RSS subscription, it only opens the feed itself in a new tab. Could you provide more details? In other words, what actions and/or situations result in the icon opening the wrong feed?

On a side note, I am aware the icon does not open the feed as expected if you navigate from a video to the channel homepage itself (and I intend to fix this issue soon). Could that be the problem you are referring to?

**Comment by teddy-gustiaux** [comment]
The [new version `1.0.2`](https://github.com/teddy-gustiaux/youtube-rss-finder/releases/tag/v1.0.2) fixes issue #4 and has gone through some code refactoring which should prevent this sort of problem from happening. 

Could you check if you are still experiencing the same issue with this new version? Thanks in advance. 🙂

**Comment by who-am-1** [comment]
can't reproduce with 1.0.2

**Comment by teddy-gustiaux** [comment]
Glad to hear it! Thanks for closing the issue. 🙂
