### ISSUE TITLE
YouTube RSS URLs now 404!

### ISSUE THREAD

**Issue by Kroc** [teddy-gustiaux/youtube-rss-finder#371]
It appears that the YouTube feeds address has moved or been removed entirely!
E.g. https://www.youtube.com/feeds/videos.xml?channel_id=UC3gRBswFkuteshdwMZAQafQ

**Comment by teddy-gustiaux** [comment]
It looks like YouTube had some temporary issues with RSS feeds. I also saw a number of my YouTube RSS feeds failing to update in my RSS reader, and returning either 404 or 500  HTTP response codes.

However, these issues appear to be resolved as of now, and all the feeds seem to be up and working again. The feed you provided in your report also works properly now.
